version: "3.9"

services:
  weatherapp:
    build: ./WeatherApp
    ports:
      - "5000:8080"
    environment:
      - ASPNETCORE_URLS=http://+:8080

  redisCache:
    image: redis:latest
    restart: always
    ports:
      - "6379:6379"
